### ISSUE TITLE
unhandled rejection

### ISSUE THREAD

**Issue by freemanuk** [carlosgamezvillegas/homebridge-zidoo-androidtv#1]
Hi, I have tried using this plugin for my Zidoo 2000 Pro, with IP and Mac address keyed in, but it's not working.  Just wonder what has gone wrong.

Below is the log:

Zidoo Androidtv Bridge starting
14/12/2023, 13:29:23Zidoo Androidtv BridgeLoaded plugin 'homebridge-zidoo-androidtv'
14/12/2023, 13:29:23Zidoo Androidtv BridgeLoading 1 platforms...
14/12/2023, 13:29:23Zidoo Androidtv BridgeWARNINGunhandled rejection: TypeError: Cannot read properties of undefined (reading 'setValue')
14/12/2023, 13:30:25WARNINGplugin site unavailable
14/12/2023, 13:32:19WARNINGplugin site unavailable

**Comment by carlosgamezvillegas** [comment]
Hello Freemanuk,

I believe that I had this issue before and I reinstalled the plugin and started working again, however, before you do that I could do some testing on my end, can you share the following:
-what operating system are you using?
-what version of Homebridge do you have?
-what plugin version did you install?
Can you please share the Homebridge Config file? Just he Zidoo section, I want to see what options are enabled.

Thank you.

**Comment by freemanuk** [comment]
Hi Carlosgamezvillegas,

I tried to reinstall the plugin twice, but it didn't help.

Anyway, I am using: 
Hoobs with Mac
Version: 4.3.0
Zidoo Androidtv Bridge 3.0.0

As a trial, I just enabled the followings:

{
    "platform": "zidooPlugin",
    "name": "Zidoo Z2000 Pro",
    "ip": "192.168.50.127",
    "mac": "80:0A:80:5C:36:C1",
    "newPlatformUUID": true,
    "powerB": true
}

**Comment by carlosgamezvillegas** [comment]
Hello @freemanuk,

I think I have solved the issue. There was a typo in the PowerB Botton and the Movie Control slider. Please install version 3.0.1 and let me know if it works for you, that way I can close this issue.

Also, in order to use custom IP and MAC you have to have this as well:
            "autoIPMac": true,
I know it is counter intuitive but I had to set it up like this so I wouldn't break some things in the code.

Kind regards,

**Comment by freemanuk** [comment]
Hi Carlosgamezvillegas,

I tried (a) updating the plugin to version 3.0.1; and (b) uninstalling and re-installing the plugin, but none helps.

Below are the latest configuration and the log:

{
    "platform": "zidooPlugin",
    "name": "Zidoo Z2000 Pro",
    "autoIPMac": true,
    "ip": "192.168.50.127",
    "mac": "80:0A:80:5C:36:C1",
    "standby": true,
    "newPlatformUUID": true,
    "powerB": true
}

20/12/2023, 13:02:48Zidoo Androidtv BridgeConfiguration change
20/12/2023, 13:02:48zidooandroidtvbridge stopping
20/12/2023, 13:02:54Zidoo Androidtv Bridge starting
20/12/2023, 13:03:04Zidoo Androidtv BridgeLoaded plugin 'homebridge-zidoo-androidtv'
20/12/2023, 13:03:04Zidoo Androidtv BridgeLoading 1 platforms...
20/12/2023, 13:03:05Zidoo Androidtv BridgeZidoo Z2000 Pro 8E28 is running on port 41429.
20/12/2023, 13:03:05Zidoo Androidtv BridgeBridge is running on port 51926.
20/12/2023, 13:04:19WARNINGplugin site unavailable
20/12/2023, 13:04:27WARNINGplugin site unavailable
20/12/2023, 13:05:02WARNINGplugin site unavailable
20/12/2023, 13:05:04WARNINGplugin site unavailable
20/12/2023, 13:05:36Zidoo Androidtv BridgeConfiguration change
20/12/2023, 13:05:36zidooandroidtvbridge stopping
20/12/2023, 13:05:41Zidoo Androidtv Bridge starting
20/12/2023, 13:05:52Zidoo Androidtv BridgeLoaded plugin 'homebridge-zidoo-androidtv'
20/12/2023, 13:05:52Zidoo Androidtv BridgeLoading 1 platforms...
20/12/2023, 13:05:52Zidoo Androidtv BridgeZidoo Z2000 Pro 8E28 is running on port 45793.
20/12/2023, 13:05:52Zidoo Androidtv BridgeBridge is running on port 51926.
20/12/2023, 13:06:04WARNINGplugin site unavailable

**Comment by carlosgamezvillegas** [comment]
Hello @freemanuk,

According to the logs, the plugin installation finishes without any issues.  The “WARNING Plugin site unavailable” error seems to be a Hoobs’ problem. If you do a quick search for that error  you  will see you are not the only one affected by this error. Luckily, Hoobs already provided a solution and  can find it here: [https://support.hoobs.org/topics/connectivity/plugin-site-unavailable](url)

I hope this solves your issue.

kind regards,

**Comment by carlosgamezvillegas** [comment]
@freemanuk, I case the link above is not taking you to the right webpage, please use copy and paste this in your browser: 
https://support.hoobs.org/topics/connectivity/plugin-site-unavailable

**Comment by freemanuk** [comment]
Have tried it, but can't have it resolved.

hoobs@hoobs:~$ sudo rm /etc/resolv.conf; sudo reboot
sudo: unable to resolve host hoobs: Temporary failure in name resolution
Connection to hoobs closed by remote host.
Connection to hoobs closed.

**Comment by carlosgamezvillegas** [comment]
Hello @freemanuk,

I am sorry you are having so many issues and nothing appears to work. The only think that I could find about that error is this: 
https://github.com/hoobs-org/HOOBS/issues/1725 
And this:
https://support.arcserve.com/s/article/KB00015380?language=en_US#:~:text=This%20issue%20can%20occur%20if,the%20%2Fetc%2Fhosts%20file.&text=To%20address%20this%20issue%20update,file%20and%20save%20the%20file.&text=Attempt%20to%20use%20the%20sudo,and%20it%20should%20work%20fine.

However, I would reach out to Hoobs to see if they can find a solution to this problem.

From my side, I think I have solve the original bug. I tested the plugin using your settings and I don’t get any errors. It is worth mentioning that I use Homebridge on a raspberry pi and not Hobby.

I hope you get to solve this issue and other plugins are not affected.

kind regards,

**Comment by freemanuk** [comment]
Hi Carlosgamezvillegas, thanks for the reply. Hopefully Hoobs can resolve the problem.
