### ISSUE TITLE
Feature request: support to override command in TV remote

### ISSUE THREAD

**Issue by maisun** [carlosgamezvillegas/homebridge-zidoo-androidtv#2]
Hi,
Thanks for the great plugin, it works very well!
Would like to raise a feature request to consider: an option to override some buttons in the TV remote 
So for example I can program the "i" button to open menu or change subtitle etc.
Also a question: why by default it adds the buttons in HK (play pause stop)? Shouldn't I use the functionality already exist in the TV remote?

Many thanks!

**Comment by carlosgamezvillegas** [comment]
Hello Maisun,

what bottoms would you like to override excactly and what options would you like to see?
Those buttons can be used  to trigger automations or control the playback using Siri. For example, you can turn off all of your lights when a movie is playing.

kind regards.

**Comment by maisun** [comment]
> Hello Maisun,
> 
> what bottoms would you like to override excactly and what options would you like to see? Those buttons can be used to trigger automations or control the playback using Siri. For example, you can turn off all of your lights when a movie is playing.
> 
> kind regards.

Hi,

Thank you for your reply! I mean a way to override the below buttons in TV remote, so I can map them to a button on Zidoo remote. For example the information button can be mapped to Menu etc. my motivation is to be able to call the menu from tv remote from where I can change audio/subtitle etc 
![IMG_4607](https://github.com/carlosgamezvillegas/homebridge-zidoo-androidtv/assets/5745785/d59f2000-9113-487a-8cfa-9449a6a87fcb)

Would it be possible to hide the default play/stop buttons? 
Thanks

**Comment by carlosgamezvillegas** [comment]
Hello,

Can you be more specific on what options you want to map on these buttons. I know you want Info—> menu. What about the other two?

If you want to hide those buttons I suggest having them to show as separate tiles and then remove them home home view.

**Comment by maisun** [comment]
> Can you be more specific on what options you want to map on these buttons. I know you want Info—> menu. What about the other two?

I actually I think that’s the only thing I need - to be able to call the menu from the TV remote. But I think it can perhaps be implemented in a generic way that users can define information -> menu, back -> subtitle etc.
I also notice two small issue with Tv remote:

(1) For some reason mute doesn’t work 
(2) Power on from TV remote sometimes get greyed out - not sure why (you can my screenshot the power button is greyed out, but switching between different TV remotes enables it again). Also I’m able to turn on the zidoo but not able to turn off from TV remote.

**Comment by carlosgamezvillegas** [comment]
I will add the option to change info to menu. Having a generic way to map the action requires a lot of time so let’s just do that.

The power and mute button in the TV Remote started to show up for non-Apple TV controllers in the latest iOS but I don’t think it is actually implemented by Homebridge, meaning that even the option is there we cannot make it work

**Comment by maisun** [comment]
Understood thanks a lot for looking into the feature and very much look forward!
Regarding power/mute I also realised it’s a new thing and my other HB plugins also haven’t supported it :-)

**Comment by carlosgamezvillegas** [comment]
Hello Maisun,

I am going to release the new update with the requested changes. Please test it out and let me know if everything is ok. 
Kind regards,

**Comment by maisun** [comment]
> Hello Maisun,
> 
> I am going to release the new update with the requested changes. Please test it out and let me know if everything is ok. Kind regards,

Thank you, I will test when it’s out!

**Comment by maisun** [comment]
I have updated to 3.1.0 and can confirm it works flawlessly - and thanks for also adding the option to remove the playback buttons!
Enjoy the weekend!
