### ISSUE TITLE
Zidoo Z9X 8K

### ISSUE THREAD

**Issue by mrota83** [carlosgamezvillegas/homebridge-zidoo-androidtv#3]
Hi i just swap  my old zidoo z9x pro for the z9x 8K. 
I needed to change the ip and mac in your plugin an now i have this error on my homebridge was working fine before.

[homebridge-zidoo-androidtv] This plugin generated a warning from the characteristic 'Volume': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.

Thank you for your help

**Comment by Etandooley** [comment]
Hello @mrota83 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID ZID07638
Please see the link below to our dedicated support line:
[Zidoo live support](https://thedappsupport.web.app/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by carlosgamezvillegas** [comment]
Hello @mrota83,

I have reached out to Zidoo to check if the API has changed for the 8K models. I will try to fix the issue once I know more about the new units.

@Etandooley, the Zidoo team actually supported this plug-in by sending me a Z9X for development.

**Comment by mrota83** [comment]
Thank you very much

**Comment by carlosgamezvillegas** [comment]
Hello @mrota83,

I have an update. The Zidoo team responded, saying they’ll reach out to us when they have a response from the engineers regarding the API. However, I believe the API has changed since the 8K devices have different capabilities in the official app. I’ll let you know if an update is possible based on the engineers response.

Kind regards,

**Comment by mrota83** [comment]
Thank you 👍

**Comment by carlosgamezvillegas** [comment]
Hello @mrota83,

I am still waiting to hear back from the Zidoo team, but I have a question about the error you are getting. If you disable the volume control, does the plug-in work correctly?

**Comment by mrota83** [comment]
Hi @carlosgamezvillegas 

The volume control is not enabled. When i get the error.

Thank you

**Comment by mrota83** [comment]
Hi @carlosgamezvillegas 

Any news from zidoo ?

**Comment by carlosgamezvillegas** [comment]
Hello @mrota83,

Unfortunately I have not heard back from them. I sent a follow up email requesting an update last Wednesday but I have not seen a replay from them yet.

I could try to publish a development version of the plugin to log the response from the device (if any) but I would need your help to provide those to figure out a fix. Are you open to helping me with this?

kind regards.

**Comment by carlosgamezvillegas** [comment]
@mrota83 
Also, I don’t know if it worth the time sending them a message stating that you are currently a Zidoo Z9X 8K and you would like to know if the  API has changed.

Here is the info:
![IMG_3192](https://github.com/user-attachments/assets/69a939e1-a6b3-496b-ad29-c239e9cb0d09)


In the past I have sent messages to Cathy, the sales team, and the support team.

Thank you,

**Comment by mrota83** [comment]
> Hello @mrota83,
> 
> 
> 
> Unfortunately I have not heard back from them. I sent a follow up email requesting an update last Wednesday but I have not seen a replay from them yet.
> 
> 
> 
> I could try to publish a development version of the plugin to log the response from the device (if any) but I would need your help to provide those to figure out a fix. Are you open to helping me with this?
> 
> 
> 
> kind regards.
> 
> 
> 
> 

Yes i can help 😃

**Comment by carlosgamezvillegas** [comment]
Hello @mrota83,

Please install the v3.1.0.test.1 version. I this version I disabled the Volume update and enabled the response log coming from the Zidoo device. Share the logs when you can.

Thank you.

**Comment by carlosgamezvillegas** [comment]
Hello @mrota83,

I have acquired a Z9X 8K and found a lot of bugs. I will release un update as soon as I test it out.

Kind regards,

**Comment by mrota83** [comment]
Hello @carlosgamezvillegas 

Sorry if i didn't get back to you. i was out of town for work.

I'm glad you're going to find out what's not working.

Thank you for your work your plugin is amazing.

**Comment by carlosgamezvillegas** [comment]
Hello @mrota83,

I have released a test version of the plugin (4.0.0-test.1). Please install it and report back if you have any issues or if you have a feature request.

Kind regards

**Comment by mrota83** [comment]
> Hello @mrota83,
> 
> 
> 
> I have released a test version of the plugin (4.0.0-test.1). Please install it and report back if you have any issues or if you have a feature request.
> 
> 
> 
> Kind regards
> 
> 

@carlosgamezvillegas 

I installed the version 4.0.0 and i get error " the devices property is not type array. Cannot initialize type:undefined "
In homekit i have no response.

**Comment by carlosgamezvillegas** [comment]
Hello @mrota83,

That is expected to happen if the device configuration is not done.  I think I added in the change log that this 4.0.0 added support to have multiple devices configured in the same network, and this in turn would break the original configuration. All you need to do to fix the issue is to configure the device again and save the changes. 

Let me know if you still have the same issues after reconfiguration the device.

Kind regards,

**Comment by mrota83** [comment]
> Hello @mrota83,
> 
> 
> 
> That is expected to happen if the device configuration is not done.  I think I added in the change log that this 4.0.0 added support to have multiple devices configured in the same network, and this in turn would break the original configuration. All you need to do to fix the issue is to configure the device again and save the changes. 
> 
> 
> 
> Let me know if you still have the same issues after reconfiguration the device.
> 
> 
> 
> Kind regards,
> 
> 

Hello @carlosgamezvillegas 

It seems to work 👍
